# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureFileCopy@2
  inputs:
    SourcePath: '$output'
    azureSubscription: 'Free Trial(f325d8f5-9869-4c6e-a17b-5204bbb1bfc7)'
    Destination: 'AzureBlob'
    storage: 'jacquesblog'
    ContainerName: '$web'