---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/_posts/writing
  label: Writing
  create: all
  match: "**/*"
- type: directory
  path: src/_posts/reading
  label: Reading
  create: all
  match: "**/*"
- type: directory
  path: src/_posts/links
  label: Links
  create: all
  match: "**/*"
  templates:
  - links
upload_dir: src/images/post-images
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm start
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
